functions:
  cpptest3:
    runtime: cpp
    desc: ""
    maintainer: ""
    handler:
      dir: ./src
      file: handler.cc
      name: Handler
    docker_registry: 10.0.0.255:5000/openfx
    image: 10.0.0.255:5000/openfx
    requests:
      memory: 50Mi
      cpu: 50m
      gpu: ""
openfx:
  gateway: 10.0.0.183:31113
